config/routes.rb
Rails.application.routes.draw do

  resources :votes
  resources :votes
  resources :trusts
  resources :tags
  get '/' => 'home#index'
  root :to => "sessions#new"


  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  get "/test_sample" => "home#rate_sample"
  get "/thankyou" => "home#thanks"

  get '/reviews/new'

  get '/upvote' => 'users#upvote', :as => 'up_vote'

  get '/downvote' => 'users#downvote', :as => 'down_vote'

  get '/items/add_tag'


  get '/users/recommend'

  get '/items/tag_item'

  get '/reviews/create'

  get '/reviews/show'

  resources :reviews
  resources :items
  resources :users
  resources :items










end

app/models/trust.rb
class Trust
  include Neo4j::ActiveRel
  property :score, type: Float
  property :from_user, type: String
  property :to_user, type: String

  from_class :User
  to_class   :User



end

app/controllers/trusts_controller.rb
class TrustsController < ApplicationController
  before_action :set_trust, only: [:show, :edit, :update, :destroy]

  # GET /trusts
  # GET /trusts.json
  def index
    @trusts = Trust.all
  end

  # GET /trusts/1
  # GET /trusts/1.json
  def show
  end

  # GET /trusts/new
  def new
    @trust = Trust.new
  end

  # GET /trusts/1/edit
  def edit
  end

  # POST /trusts
  # POST /trusts.json
  def create
    @trust = Trust.new(trust_params)

    respond_to do |format|
      if @trust.save
        format.html { redirect_to @trust, notice: 'Trust was successfully created.' }
        format.json { render :show, status: :created, location: @trust }
      else
        format.html { render :new }
        format.json { render json: @trust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trusts/1
  # PATCH/PUT /trusts/1.json
  def update
    respond_to do |format|
      if @trust.update(trust_params)
        format.html { redirect_to @trust, notice: 'Trust was successfully updated.' }
        format.json { render :show, status: :ok, location: @trust }
      else
        format.html { render :edit }
        format.json { render json: @trust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trusts/1
  # DELETE /trusts/1.json
  def destroy
    @trust.destroy
    respond_to do |format|
      format.html { redirect_to trusts_url, notice: 'Trust was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trust
      @trust = Trust.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trust_params
      params.require(:trust).permit(:score)
    end
end

app/helpers/trusts_helper.rb
module TrustsHelper
end

app/views/trusts/_form.html.erb
<%= form_for(@trust) do |f| %>
  <% if @trust.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trust.errors.count, "error") %> prohibited this trust from being saved:</h2>

      <ul>
      <% @trust.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trusts/edit.html.erb
<h1>Editing Trust</h1>

<%= render 'form' %>

<%= link_to 'Show', @trust %> |
<%= link_to 'Back', trusts_path %>

app/views/trusts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trusts</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trusts.each do |trust| %>
      <tr>
        <td><%= trust.score %></td>
        <td><%= link_to 'Show', trust %></td>
        <td><%= link_to 'Edit', edit_trust_path(trust) %></td>
        <td><%= link_to 'Destroy', trust, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trust', new_trust_path %>

app/views/trusts/new.html.erb
<h1>New Trust</h1>

<%= render 'form' %>

<%= link_to 'Back', trusts_path %>

app/views/trusts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @trust.score %>
</p>

<%= link_to 'Edit', edit_trust_path(@trust) %> |
<%= link_to 'Back', trusts_path %>