config/routes.rb
Rails.application.routes.draw do

  resources :votes
  resources :votes
  resources :trusts
  resources :tags
  get '/' => 'home#index'
  root :to => "sessions#new"


  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  get "/test_sample" => "home#rate_sample"
  get "/thankyou" => "home#thanks"

  get '/reviews/new'

  get '/upvote' => 'users#upvote', :as => 'up_vote'

  get '/downvote' => 'users#downvote', :as => 'down_vote'

  get '/items/add_tag'


  get '/users/recommend'

  get '/items/tag_item'

  get '/reviews/create'

  get '/reviews/show'

  resources :reviews
  resources :items
  resources :users
  resources :items










end

app/models/item.rb
class Item 
  include Neo4j::ActiveNode
  property :name, type: String ,constraint: :unique
  property :description, type: String
  property :picture_url, type: String

  has_many :in, :reviews, rel_class: :Review

  has_many :in, :tags, origin: :items

  def avg_rating
    sum = 0.0
    reviews = self.reviews.each_rel{|r|}
    reviews.each do |rev|
      sum = sum + rev.stars.to_f

    end
    @avg_rating = sum/self.reviews.count
  end

  def self.get_test_sample
    outdoors_tag = Tag.find_by(name: "Aire Libre")
    snow_tag = Tag.find_by(name: "Nieve")
    urban_tag = Tag.find_by(name: "Urbano")
    historic_tag = Tag.find_by(name: "Histórico")
    artistic_tag = Tag.find_by(name: "Artístico")

    outdoors = outdoors_tag.items
    snow = snow_tag.items
    urban = urban_tag.items
    historic = historic_tag.items
    artistic = artistic_tag.items

    sample = []
    [outdoors,snow,urban,historic,artistic].each do |tag|
      random_item = tag[rand(0..tag.size-1)]
      added_to_sample = 0

      until (added_to_sample == 2) do
        unless sample.include? random_item
          sample << random_item
          added_to_sample += 1
        else
          random_item = tag[rand(0..tag.size-1)]
        end
      end
    end
    return sample
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @tags = Tag.all

    #@item.tags = @tages[1]

  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tag_item
    @tags = Tag.all
    @item = Item.find_by(name: params[:format])
  end

  def add_tag
    @le_item = Item.find_by(name: params[:item])
    @le_tag = Tag.find_by(name: params[:tag])
    @le_item.tags << @le_tag
    redirect_to items_path

  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :picture_url, :item, :tag)
    end
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :picture_url %><br>
    <%= f.text_field :picture_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/add_tag.erb
<p id="notice"><%= notice %></p>

<h1>Yay</h1>



<%= params.inspect %>
<%= @le_item.inspect %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.picture_url %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.haml
- @all_reviews = @item.reviews.each_rel{|r| }
- cu_has_review = false
- @all_reviews.each do |review|
  -if review.from_node.id == current_user.id
    - @review_from_cu = review
    - cu_has_review = true
.container
  .row
    .col-md-9
      .thumbnail
        %img.img-responsive{src: "#{@item.picture_url}", width:'800px', height:'300px'}
        .caption-full
          %h4
            %a{:href => "#"}= @item.name
          %p
            = @item.description
          %p
            %strong Tags:
            - @item.tags.each do |tage|
              %tr
                %td= tage.name
            %tr
              = link_to 'Add Tag',items_tag_item_path(@item.name)
            .ratings
              %p.pull-right
                = @item.reviews.count
                reviews
              %p
                Average Score:
                %input{type:"hidden", class:"avg-stars", 'data-readonly': "#{@item.avg_rating}" }
            .well
              .pull-left
                %h4 User Reviews
              .text-right
                - if  !cu_has_review
                  = link_to new_review_path(@item.name), remote: true do
                    %button.btn.btn-success Add a Review
                - else
                  Your Review:
                  = render 'reviews/edit_form', review: @review_from_cu
              %hr
              .row
                #review-form{:style => "display:none;"}
              %hr
              - @all_reviews.each do |review|
                .row
                  .col-md-12
                    .review
                      %input#input_review{"data-readonly" => "#{review.stars}", :type => "hidden"}
                    = review.from_node.name
                    %span.pull-right
                      - if review.from_node.votes.each_rel.select{ |r| r.to_item == @item.name }.any?
                        %td Upvoted
                      - else
                        %td= link_to 'Upvote,',up_vote_path(:current_item => @item.id,:target_user => review.from_node.name)
                      - if review.from_node.votes.each_rel.select{ |r| r.to_item == @item.name }.any?
                        %td Downvoted
                      - else
                        %td= link_to 'Downvote,',down_vote_path(:current_item => @item.id,:target_user => review.from_node.name)
                    %p= review.content
:javascript
  $( ".avg-stars" ).each(function( ) {
    var score =  parseInt($(this).attr('data-readonly'));
    console.log(score);
    $( this ).rating('rate', score);
  });

  $('.edit_review').submit(function(event) {

    /* stop form from submitting normally */
  event.preventDefault();

  /* get values from elements on the page: */
  var from_user = $('#review_from_user').val();
  var to_item = $('#review_to_item').val();
  var content = $('#review_content').val();
  var stars = $('#input-id').val();
  var id = $('#review_id').text();

  var url = "/reviews/"+id
  console.log(url)

  /* Send the data using post and put the results in a div */
  $.ajax({
    url: url,
    type: "put",
    dataType: "html",
    data: { review: { from_user: from_user, to_item: to_item,content: content,stars:stars } },
    success: function() {
      location.reload();
    },
    });
    return false;
  });

app/views/items/tag_item.html.erb
<p id="notice"><%= notice %></p>

<h1>Avaliable Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>

    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tage| %>
      <tr>
        <td><%= tage.name %></td>

        <td><%= link_to 'Tag', items_add_tag_path(:tag => tage.name,:item => @item.name) %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= @item.inspect %>

<%= link_to 'Add Tag', new_tag_path %>